# originally sourced from: https://github.com/jackal/jackal/blob/noetic-devel/jackal_control/config/teleop_ps4.yaml
# Teleop configuration for PS4 joystick using the x-pad configuration.
teleop_node:
  axis_linear: 1
  scale_linear: 0.3
  scale_linear_turbo: 0.6
  axis_angular: 0
  scale_angular: 0.6
  enable_button: 4
  enable_turbo_button: 5
joy_node: 
  deadzone: 0.1
  autorepeat_rate: 5